jobs:
  - name: "List tmp directory"
    command: "ls -la /tmp"
    schedule: "0 */1 * * * *"
    retries: 2
    timeout: 10            

  - name: "Failing job test"
    command: "exit 1"
    schedule: "0 */2 * * * *"
    retries: 1
    timeout: 5             
